version: "3"
   
services:
  checkout-api:
    #network_mode: host
    container_name: checkout-api
    build: ./checkout-api/
    command: python ./checkout-api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"

networks:
 default:
   external:
      name: microservice